[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_PRIVATE_TARGET = "server"

# Handle ESLint warnings but don't fail the build
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ssh2"]
  included_files = ["lib/**"]

[functions."api/mt5/connect"]
  timeout = 30
  memory = 1024
  maxDuration = 30

# Remove the redirects since we're using Next.js API routes
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

[dev]
  framework = "next"
